### ISSUE TITLE
xcode version issue

### ISSUE THREAD

**Issue by nmashni** [dequelabs/Deque-University-for-iOS#51] opened 2018-11-08 14:16 UTC
![screen shot 2018-11-07 at 11 31 55 am](https://user-images.githubusercontent.com/32878595/48204009-da990280-e336-11e8-9a40-8167f5e64bdd.png)

Hello,

I’m still having issues running the test project. 
I’m sharing a screenshot with the error and the Bash_Profiile file
Also tried to build the project without the XCode version, or with a different build, tried to follow your instructions closely

My XCode version is Version 9.2 (9C40b). Do you have any instructions or suggestions?

**Comment by nmashni** [comment] 2018-11-08 15:16
We resolved this by having him manually download the attest framework zip from artifactory, and building it locally. 

he also had an issue where his device was running iOS 9 and the build was choking on that.  

updating his iOS version, with the local framework zip, fixed this issue.

**Comment by chriscm2006** [comment] 2018-11-08 18:09
@jldailey13 I'm concerned about the following.

![screen shot 2018-11-08 at 1 07 49 pm](https://user-images.githubusercontent.com/3856068/48218223-6589f500-e357-11e8-9af3-31dd7f4d381e.png)

I would expect that there be a JSON in there of the available Xcode versions and also later in the image available build artifacts for those versions. 

I don't know the conditions in which curl would fail silently. We should investigate this more thoroughly.

**Comment by chriscm2006** [comment] 2018-11-08 18:13
This is a duplicate of #50 

A customer opened that issue, we should keep conversation there. Also, the lack of screen shots means that issue is more accessible. I'm going to massage the customers posted issue slightly. Let's close this and resolve against that issue.

**Closed by chriscm2006** 2018-11-08 18:13 UTC
Labels: Attest-iOS, Duplicate :man_facepalming:, FAQ :question:
